App/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views #necesario para la contraseña
from .mercadopago import create_preference
urlpatterns = [
    #pantallas
    path( '',Home,name='inicio'),
    path('contacto/',Contacto,name='contacto'),
    path('nosotros/',Nosotros,name='nosotros'),
    #carrito
    path('carrito/<id_producto>/',AgregarCarrito,name='compcarrito'),
    path('carrito/',VerCarrito ,name='carrito'),
    path('carrito/eliminar/<pk_carritodet>/',EliminarCarrito ,name='carritoE'),
    path('carrito/modificar/<int:pk_carritodet>/', ModificarCantidad, name='modificar_cantidad'),
    path('comprar/<int:id_producto>/<int:pk_carritodet>',comprar_producto ,name='comprar'),
    path('pagar/<pk_carritodet>/',payment,name='payment'),
    path('pagar/',payment,name='paymentfull'),
    path('comprar_todo_carrito/',comprar_todo_carrito,name='comprar_todo_carrito'),
    #productos
    path('productos/',ver_Productos,name='visualizar'),
    path('agregar/',Agregar,name='agregar'),
    path('modificar/<id_producto>/',Modificar_Productos,name='modificar'),
    path('eliminar/<id_producto>/',Eliminar_Productos,name='eliminar'),
    path('producto/<id_producto>/',verMas,name='vermas'),
    #usuario
    path('logouts/',salir,name='logouts'),
    path('register/', register, name='register'),
    path('mails/',Gmail,name='gmail'),
    path('profile/',user_profile,name='profile'),
    #reseteo de contraseña
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    #mercadopago
    path("create_preference/",create_preference, name="preference")
]

Proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

#--->Importar Settings
from django.conf import settings
#---> Importamos Static
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('App.urls')),
    #--->Para las URL de Login/Logout
    path('accounts/',include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

App/models.py
from django.db import models
from ckeditor import fields
from django.contrib.auth.models import User
# Create your models here.
class Productos(models.Model):
    id_producto = models.AutoField(primary_key=True)
    nom_producto = models.TextField(max_length=50, null=False)
    desc_producto = fields.RichTextField(null=True)
    precio_producto = models.IntegerField(null=False)
    stock_producto = models.IntegerField(null=False)
    imagen_producto = models.ImageField(null=False,upload_to="productos", default="")
    def __int__ (self):
        return self.id_producto

class Carrito(models.Model):
    carrito_id = models.AutoField(primary_key=True, null=False)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __int__(self):
        return self.carrito_id
    
class Carrito_detalle(models.Model):
    pk_carritodet = models.AutoField(primary_key=True, null=False)
    carrito_det = models.ForeignKey(Carrito, on_delete=models.CASCADE, null=False)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField(default=1)
    def __str__(self):
        return f"Carrito de {self.carrito_det.user} con el producto {self.producto.nom_producto}"
class ImagenesProductos(models.Model):
    Imagen=models.ImageField(upload_to="productos")
    Codigo=models.ForeignKey(Productos,on_delete=models.CASCADE,related_name="Imagenes")
class Compra(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    producto = models.ForeignKey(Productos, on_delete=models.CASCADE)
    cantidad = models.PositiveIntegerField()
    fecha = models.DateTimeField(auto_now_add=True)
    precio_total = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"Compra de {self.producto.nom_producto} por {self.usuario.username}"

App/templates/index.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stanley Web Site</title>
    <!-- Hoja de Estilos -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <!-- Hoja de Estilos de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
    {% for i in messages %}

    {% endfor %}
    <nav class="py-2 bg-body-tertiary border-bottom">
        <div class="container d-flex flex-wrap">
            <a href="{% url 'inicio' %}" class="d-flex align-items-center mb-3 mb-lg-0 me-lg-auto link-body-emphasis text-decoration-none">
                <img class="bi me-2" width="40" height="32" src="{% static 'img/index/panda.png' %}" alt="stanley logo"><use xlink:href="#bootstrap"></use>
                <img class="bi me-2" width="80" src="{% static 'img/index/letras.png' %}" alt="stanley logo"><use xlink:href="#bootstrap"></use>
              </a>
          <ul class="nav me-auto">
            <li class="nav-item"><a href="{% url 'inicio' %}" class="nav-link link-body-emphasis px-2 active" aria-current="page">Inicio</a></li>
            <li class="nav-item"><a href="{% url 'visualizar' %}" class="nav-link link-body-emphasis px-2">Productos</a></li>
            <li class="nav-item"><a href="{% url 'nosotros' %}" class="nav-link link-body-emphasis px-2">Nosotros</a></li>
            <li class="nav-item"><a href="{% url 'contacto' %}" class="nav-link link-body-emphasis px-2">Contacto</a></li>
            {% if perms.App.add_productos %}
            <li class="nav-item"><a href="{% url 'agregar' %}" class="nav-link link-body-emphasis px-2">Agregar</a></li>
            {% endif %}

            <form class="col-12 col-lg-auto mb-3 mb-lg-0" role="search" method="get" action="{% url 'visualizar' %}">
                <input type="search"  class="form-control" name="filtro" placeholder="Buscar..." aria-label="Search">
              </form>
          </ul>
          <ul class="nav">
            {% if user.is_authenticated %}
            
            <li class="nav-item"><a class="nav-link link-body-emphasis px-2 mx-2" href="{% url 'carrito' %}" id="contacto_btn"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><rect width="24" height="24" fill="none"/><path fill="currentColor" d="M17 18c-1.11 0-2 .89-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2a2 2 0 0 0-2-2M1 2v2h2l3.6 7.59l-1.36 2.45c-.15.28-.24.61-.24.96a2 2 0 0 0 2 2h12v-2H7.42a.25.25 0 0 1-.25-.25q0-.075.03-.12L8.1 13h7.45c.75 0 1.41-.42 1.75-1.03l3.58-6.47c.07-.16.12-.33.12-.5a1 1 0 0 0-1-1H5.21l-.94-2M7 18c-1.11 0-2 .89-2 2a2 2 0 0 0 2 2a2 2 0 0 0 2-2a2 2 0 0 0-2-2"/></svg>Carrito</a></li>
            <li class="nav-item"><a class="nav-link link-body-emphasis px-2" href="{% url 'logouts' %}" id="contacto_btn"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><rect width="24" height="24" fill="none"/><path fill="currentColor" d="M19 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2V5a2 2 0 0 0-2-2m-3.4 14L12 13.4L8.4 17L7 15.6l3.6-3.6L7 8.4L8.4 7l3.6 3.6L15.6 7L17 8.4L13.4 12l3.6 3.6z"/></svg>Cerrar Sesión</a></li>
            <li class="nav-item"><a class="nav-link link-body-emphasis px-2 mx-2" href="{% url 'profile' %}" id="contacto_btn"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path fill="currentColor" d="M12 4a4 4 0 0 1 4 4a4 4 0 0 1-4 4a4 4 0 0 1-4-4a4 4 0 0 1 4-4m0 10c4.42 0 8 1.79 8 4v2H4v-2c0-2.21 3.58-4 8-4"/></svg>{{ user.username }}</a></li>
            
            {% else %}
            <li class="nav-item"><a class="nav-link link-body-emphasis px-2" href="{% url 'login' %}" id="contacto_btn">Ingresar</a></li>
            {% endif %}
          </ul>
        </div>
      </nav>
    {% if err %}
    <script>
            Swal.fire({
                icon: "error",
                title: "Oops...",
                text: "{{err}}",
            });
    </script>
    {% endif %}
    {% if accepted %}
    <script>
            Swal.fire({
                icon: "success",
                title: "Producto Añadido al Carrito",
                text: "{{accepted}}",
            });
    </script>
    {% endif %}
        {% block intermedio %}
        <div id="myCarousel" class="carousel slide mb-6" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="0" aria-label="Slide 1" class="active" aria-current="true"></button>
              <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="1" aria-label="Slide 2" class=""></button>
              <button type="button" data-bs-target="#myCarousel" data-bs-slide-to="2" aria-label="Slide 3" class=""></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                 <img src="{% static 'img/image.png' %}" width="100%" height="500px" object-fit:"cover" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" alt="">
                <div class="container">
                {% if user.is_authenticated %}
                <div class="carousel-caption text-start">
                    <h1>Mira nuestro catalogo.</h1>
                    <p class="opacity-75">Para poder conseguir hoy los mejores productos para el mate.</p>
                    <p><a class="opacity-75 btn btn-lg btn-primary" href="{% url 'visualizar' %}">Ver Catalogo</a></p>
                  </div>
                {% else %}
                <div class="carousel-caption text-start">
                    <h1>Unete a Stanley 1913.</h1>
                    <p class="opacity-75">Para poder conseguir hoy los mejores productos para el mate.</p>
                    <p><a class="opacity-75 btn btn-lg btn-primary" href="{% url 'login' %}">Registrarse</a></p>
                  </div>
                {% endif %}
                </div>
              </div>
              <div class="carousel-item ">
                <img src="{% static 'img/carrousel/4.jpg' %}" width="100%" height="500px" object-fit:"cover" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" alt="">
                <div class="container">
                  <div class="carousel-caption">
                    <h1>Los mejores termos del mundo.</h1>
                    <p>Consigue el tuyo aquí.</p>
                    <p><a class="btn btn-lg btn-primary opacity-75" href="{% url 'visualizar' %}">Catalogo</a></p>
                  </div>
                </div>
              </div>
              <a href="{% url 'visualizar' %}">
              <div class="carousel-item">
                <img src="{% static 'img/carrousel/6.png' %}" width="100%" height="500px" object-fit:"cover" aria-hidden="true" preserveAspectRatio="xMidYMid slice" focusable="false" alt="">
              </div>
            </a>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#myCarousel" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#myCarousel" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        {% endblock %}
    <main class="contenedor_general">
        {% block cuerpo %}

        <h1 class="subtitulo_index">Ultimos Productos</h1>
        <div class="contenedor_visualizar m-auto">

            {% for i in forms %}

            <div class="card" style="width: 18rem;">
                <!-- Pasamos la Ruta de la Imagen Registrada -->
                <img src="{{i.imagen_producto.url}}" class="card-img-top" style="max-height: 200px; object-fit: contain;" alt="Imagen BD">
                <div class="card-body">
                  <h4 class="card-title">{{i.nom_producto}}</h4>
                  <h5 class="card-text">${{i.precio_producto}}</h5>
                  <a
            id=""
            class="btn btn-secondary"
            href="{% url 'vermas' i.id_producto %}"
            role="button"
        ><i style="font-size: 20px;" class="bi bi-cart"></i>Ver Más</a>
                </div>
              </div>
              {% endfor %}
              
        </div>
        <div class="contenedor_visualizar">
            <a
            id=""
            class="btn btn-danger w-50"
            href="{% url 'visualizar' %}"
            role="button"
        >Ver Productos</a>
            {% endblock %}
        </div>
        
        
    </main>
    <footer class="bg-light text-center py-4">
        <div class="container">
            <!-- Logo de la Empresa -->
            <div class="mb-3">
                <img src="{% static 'img/index/panda.png' %}" alt="Logo de la Empresa" class="img-fluid" style="max-width: 150px;">
            </div>
    
            <!-- Información de Contacto -->
            <div class="mb-3">
                <h5>Contacto</h5>
                <p>Email: <a href="mailto:contacto@stanley.com">contacto@stanley.com</a></p>
                <p>Teléfono: 11 4456-7890</p>
            </div>
    
            <!-- Iconos de Redes Sociales -->
            <div class="mb-3 btn-group">
                <a href="https://www.instagram.com" target="_blank" aria-label="Instagram" class="btn btn-outline-secondary">
                    <i style="font-size: 24px;" class="bi bi-instagram"></i>
                </a>
                
                <!-- Icono de Facebook -->
                <a href="https://www.facebook.com" target="_blank" aria-label="Facebook" class="btn btn-outline-secondary">
                    <i style="font-size: 24px;" class="bi bi-facebook"></i>
                </a>
            
                <!-- Icono de WhatsApp -->
                <a href="https://www.whatsapp.com" target="_blank" aria-label="WhatsApp" class="btn btn-outline-secondary">
                    <i style="font-size: 24px;" class="bi bi-whatsapp"></i>
                </a>
            
                <!-- Icono de Twitter -->
                <a href="https://twitter.com" target="_blank" aria-label="Twitter" class="btn btn-outline-secondary">
                    <i style="font-size: 24px;" class="bi bi-twitter"></i>
                </a>
            </div>
    
            <!-- Derechos de Autor -->
            <div class="text-muted">
                <p>&copy; 2024 Stanley&trade;. Todos los derechos reservados.</p>
            </div>
        </div>
    </footer>
    
    <!-- Hoja de Acciones de Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>

</html>